### ISSUE TITLE
Ctrl-N and Ctrl-P not working

### ISSUE THREAD

**Issue by LunEyx** [ncm2/ncm2#10]
If you're having trouble with NCM2, Please provide the following information
along with your detailed issue description:

### OS

MacOS 10.13.5

### neovim `:version` output

0.3.0

### Minimal vimrc for reproducing the issue

```
Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'

autocmd BufEnter * call ncm2#enable_for_buffer()
set completeopt=noinsert,menuone,noselect
```

### Issue

Ctrl-N and Ctrl-P do not popup vim's original auto-complete.

If it is a feature, I think there should be a switch to turn it off.

**Comment by roxma** [comment]
It should be easier to work with builtin completion after https://github.com/ncm2/ncm2/pull/28#issuecomment-405146245 is merged

```vim
    au User Ncm2PopupOpen set completeopt=noinsert,menuone,noselect
    au User Ncm2PopupClose set completeopt=menuone
```
