### ISSUE TITLE
[feature request] tags support

### ISSUE THREAD

**Issue by zackhsi** [ncm2/ncm2#100]
It doesn't appear that ncm2 or the related plugins support `tags` files. If I'm reading correctly, this was supported in nvim-completion-manager with the [cm_tags](https://github.com/roxma/nvim-completion-manager/blob/master/pythonx/cm_sources/cm_tags.py) file.

Opening this issue to track the work of supporting `tags`.

Thanks for a great project!

**Comment by roxma** [comment]
https://github.com/ncm2/ncm2-tagprefix
