### ISSUE TITLE
`inoremap jk <esc>` not work when input quickly

### ISSUE THREAD

**Issue by ZSaberLv0** [ncm2/ncm2#104]
by `inoremap jk <esc>` and:

* input `calljk` quickly, would result `calljk` and remain in insert mode
* input `call` and wait for a while, after the popup completely updated, then input `jk`, would correctly exit insert mode
* if use `<esc>` instead, everything works fine, no matter when you input `<esc>`

changing `let g:ncm2#complete_delay=50` would prevent the issue when input quickly,
but if the `jk` pressed within the duration of the popup update,
the issue would also happen

the "popup update duration" typically has considerable length, 300ms in my feeling,
causing the `jk` nearly unable to use

**Comment by roxma** [comment]
hmm...

It is the side effect of  `feedkeys("\<Plug>(ncm2_complete_popup)")`, I guess.

**Comment by ZSaberLv0** [comment]
@roxma after a bunch of test, it seems only occurred on vim8, won't happen on neovim

my envs that issue occur:

* Windows gVim 8.1.1
* MacOS vim 8.1.500

my envs that issue won't occur:

* MacOS neovim 0.3.0
* CentOS7 neovim 0.3.0
