### ISSUE TITLE
[feature request] blacklist

### ISSUE THREAD

**Issue by rebelot** [ncm2/ncm2#109]
would it be possible to have a blacklist key to disable certain sources for specific filetypes instead of specifying every ft to which a source should apply? or is there currently any convenient method to achieve that?

i.e. `ncm2#override_source('tmux-complete', { 'blacklist' : [ 'latex' ] })`

thanks

**Comment by roxma** [comment]
Kind of duplicated  #3 

I'll increase the priority of this feature.
