### ISSUE TITLE
Do not insert method parameters

### ISSUE THREAD

**Issue by edganiukov** [ncm2/ncm2#117]
I use ncm2 with ncm2-vim-lsp and vim-lsp plugins. As a language server I use bingo (https://github.com/saibing/bingo).  The problem is, bingo returns methods with its signature and ncm2 inserts it while completion (see attachment). I think it would be good to insert only method name, without signature and parenthesis.
<img width="752" alt="screen shot 2019-01-04 at 19 10 20" src="https://user-images.githubusercontent.com/1741939/50705613-a94d6200-105b-11e9-8813-2b69c27f7783.png">

**Comment by roxma** [comment]
A workaround for now: install [ncm2-ultisnips](https://github.com/ncm2/ncm2-ultisnips) or [ncm2-snipmate](https://github.com/ncm2/ncm2-snipmate) and use the snippet feature.

The completion item returned by `bingo` looks like this. There's no way for ncm2 to figure out `After` instead of `After(d time.Duration)`. 

```json
{
	"label": "After(d time.Duration)",
	"detail": "<-chan time.Time",
	"insertTextFormat": 2,
	"insertText": "After(${1:d time.Duration})",
	"sortText": "00001",
	"kind": 3,
	"textEdit": {
		"range": {
			"start": {
				"character": 7,
				"line": 183
			},
			"end": {
				"character": 12,
				"line": 183
			}
		},
		"newText": "After(${1:d time.Duration})"
	}
}
```

**Comment by roxma** [comment]
Add this to your vimrc if you need to remove the `(...)` stuff for completion.

```vim
call ncm2#override_source('bingo', {'filter': {'name':'substitute',
                    \ 'pattern': '[\(\s].*$',
                    \ 'replace': '',
                    \ 'key': 'word'}})
```

**Comment by edganiukov** [comment]
Thanks, works for me, I end up with next filter:
```
call ncm2#override_source('bingo', {'filter': {'name':'substitute',
    \ 'pattern': '^([a-zA-Z0-9_]+).*',
    \ 'replace': '\1',
    \ 'key': 'word'}})
```
