### ISSUE TITLE
[Feature Request] Sorting by type (e.g variables, methods).

### ISSUE THREAD

**Issue by edganiukov** [ncm2/ncm2#118]
I find it useful to have completion sorted by type - e.g. first suggest const, variables and fields, then methods, and groups of suggestions sort by already implemented sorting algorithm (e.g. abbrfuzz).

**Comment by roxma** [comment]
This doesn't seem common usage. You could define your own filter like https://github.com/ncm2/ncm2/blob/99600eeda88161bcb0058acf7595cc6f3935f68e/pythonx/ncm2_filter/substitute.py    for  #117 

```python
def Filter(**kargs):
    def filt(data, sr, sctx, sccol, matches):
        matches.sort(key=...)
        return matches
    return filt
```
