### ISSUE TITLE
can not complete go local package's symbols

### ISSUE THREAD

**Issue by butterflyfish** [ncm2/ncm2#12]
If you're having trouble with NCM2, Please provide the following information
along with your detailed issue description:

### OS
Mac

### neovim `:version` output
```
NVIM v0.3.1-149-g44a284d71
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DM
IN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protec
tor-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM
 -I/tmp/neovim-20180710-39753-gv71d5/build/config -I/tmp/neovim-20180710-39753-gv71d5/src -I/usr/local/include -I/usr/local/opt/gettext
/include -I/usr/include -I/tmp/neovim-20180710-39753-gv71d5/build/src/nvim/auto -I/tmp/neovim-20180710-39753-gv71d5/build/include
Compiled by michael@Michaels-MacBook-Pro-3022.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-44a284d/share/nvim"
```

### Minimal vimrc for reproducing the issue
follow readme

Plugin: LanguageClient-neovim/go-languageserver

after input local package name with dot, it complains error. but it works wee on 1st generation of ncm and deoplete. After save file, then press 'a' to append after dot, completion menu pop up.

![image](https://user-images.githubusercontent.com/14833825/42500656-7651babe-8464-11e8-8c73-4ef9c198399a.png)

**Comment by roxma** [comment]
I believe that's go-langserver issue. If you append a space after the cursor, the completion works fine.

ncm2 works fine with rls.
