### ISSUE TITLE
[feature request] remove duplicates

### ISSUE THREAD

**Issue by flagello** [ncm2/ncm2#120]
Use case: Rust’s language server appears to send duplicate signatures in some circumstances (e.g., `Vec::`) (tested with `LanguageClient-neovim` and `vim-lsp`).

**Comment by roxma** [comment]
This doesn't seem common. Perhaps there're function overloading and it makes harder for completion plugin to check the duplication.

You could define your own filter like https://github.com/ncm2/ncm2/blob/99600eeda88161bcb0058acf7595cc6f3935f68e/pythonx/ncm2_filter/substitute.py for #117

**Comment by flagello** [comment]
Rust does not support function overloading. I’ll consider a filter, thanks!

**Comment by roxma** [comment]
I have added a set_dup filter, usage:

```vim
call ncm2#override_source('bufword', {'filter': [{'name': 'set_dup', 'value': 0}]}) 
```
