### ISSUE TITLE
:echo has(‘python3’) returns ‘0’, but python 3 is installed 

### ISSUE THREAD

**Issue by chrisvacc** [ncm2/ncm2#125]
**OS - macOS Mojave**

**NVIM v0.2.2**
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion
 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_H
AS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-param
eter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protect
or-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovi
m-20180209-92407-udkzoo/neovim-0.2.2/build/config -I/tmp/neovim-20180209-92407-u
dkzoo/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/in
clude -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/loca
l/opt/gettext/include -I/usr/include -I/tmp/neovim-20180209-92407-udkzoo/neovim-
0.2.2/build/src/nvim/auto -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build
/include
Compiled by brew@HighSierra.local

**Also error:**
Error detected while processing BufEnter Auto commands for "*":
E117: Unknown function: ncm2#enable_for_buffer
E117: Unknown function: ncm2#enable_for_buffer
E117: Unknown function: ncm2#enable_for_buffer
E117: Unknown function: ncm2#enable_for_buffer

**Comment by roxma** [comment]
> :echo has(‘python3’) returns ‘0’, but python 3 is installed

`pip install pynvim`

`:help provider-python`

**Comment by chrisvacc** [comment]
python3 -m pip --version

pip 18.1 from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip (python 3.7)

But i guess I’ll ask them.

**Comment by chrisvacc** [comment]
```
pip install pynvim
Requirement already satisfied: pynvim in /usr/local/lib/python2.7/site-packages (0.3.1)
Requirement already satisfied: trollius in /usr/local/lib/python2.7/site-packages (from pynvim) (2.2)
Requirement already satisfied: msgpack>=0.5.0 in /usr/local/lib/python2.7/site-packages (from pynvim) (0.5.6)
Requirement already satisfied: greenlet in /usr/local/lib/python2.7/site-packages (from pynvim) (0.4.13)
Requirement already satisfied: six in /usr/local/lib/python2.7/site-packages (from trollius->pynvim) (1.12.0)
Requirement already satisfied: futures in /usr/local/lib/python2.7/site-packages (from trollius->pynvim) (3.2.0)
```

**Comment by chrisvacc** [comment]
Wait, it works.. thanks!!!
