### ISSUE TITLE
Pop-up menu flickering in Vim 8 with syntax on

### ISSUE THREAD

**Issue by jsit** [ncm2/ncm2#131]
With `syntax on`, the pop-up menu from ncm2 in Vim 8 (8.1 with patch 750) "flickers" when typing characters in a file with a lot of content; each time a new key is pressed, the entire pum seems to reload and refresh, sometimes with non-matching candidates before those candidates are dropped after another refresh. Turning `syntax off` solves this issue.
 
Here's a GIF demonstrating the issue with neocomplete snippets; you can see the word `-- INSERT --` blinking too. I also have much longer snippets in a file that unfortunately is under NDA, but with those the problem is exacerbated:

![2019-01-29 12 18 31](https://user-images.githubusercontent.com/643417/51926844-34eab200-23c0-11e9-9eb7-9265861c16a1.gif)

Here it is with bufword completion, with syntax on and then off:

![2019-01-29 12 25 53](https://user-images.githubusercontent.com/643417/51927242-2d77d880-23c1-11e9-8f29-2b8a4da2b693.gif)

In an empty file, or when the highlighted code is "off screen" -- i.e., if you add enough blank lines to the end of the file so that the syntax-highlighted code is out of view -- the problem also disappears.

I'm using iTerm2 Build 3.2.1beta4 on macOS Mojave 10.14.2

Minimal `.vimrc`:

```vim
set nocompatible
filetype plugin on
filetype indent on
syntax on

" plugins
set runtimepath+=~/.vim/bundle/ncm2
set runtimepath+=~/.vim/bundle/nvim-yarp
set runtimepath+=~/.vim/bundle/vim-hug-neovim-rpc
set runtimepath+=~/.vim/bundle/ncm2-neosnippet
set runtimepath+=~/.vim/bundle/ncm2-bufword
set runtimepath+=~/.vim/bundle/neosnippet.vim

" ncm2
autocmd BufEnter * call ncm2#enable_for_buffer()
let g:ncm2#popup_delay = 200
let g:ncm2#complete_delay = 0
set completeopt=noinsert,menuone,noselect

" neosnippet
let g:neosnippet#disable_runtime_snippets = {  '_' : 1,  }
let g:neosnippet#snippets_directory="~/.vim/bundle/neosnippet-snippets/neosnippets"
```

**Comment by roxma** [comment]
Could you try Vim 8.1.0768 mentioned in https://github.com/vim/vim/issues/1713#issuecomment-455793603?

**Comment by jsit** [comment]
I'm getting the same issue in Vim 8.1.0800

**Comment by jsit** [comment]
Still seems to be happening on that branch for me

**Comment by roxma** [comment]
hmm... There's not much I can do then. This is a known vim/neovim "issue", as mentioned in  vim/vim#1713 

If you do think  that it is really annoying, you could try `g:ncm2#matcher="prefix"`. But then you would loose fuzzy completion feature.

An alternative, perhaps, is to bring back `completefunc` implementation mentioned in https://github.com/roxma/nvim-completion-manager/issues/8#issuecomment-279307099 .

**Comment by roxma** [comment]
You could try https://github.com/ncm2/ncm2/pull/135
You need to  manually compile this version of vim: https://github.com/vim/vim/pull/3887

**Comment by roxma** [comment]
By the way, for css completion, you might need `set iskeyword=@,$,48-57,_,192-255,-` to prevent vim/nvim from closing the popup automatically with the `-` character.

**Comment by roxma** [comment]
Closing inactive issue
