### ISSUE TITLE
[Question] How to make ncm2 work with OmniSharp (C#)?

### ISSUE THREAD

**Issue by trobjo** [ncm2/ncm2#138]
### neovim `:version` output:
https://transfer.sh/YUvRD/version.txt
### Minimal vimrc for reproducing the issue:
https://transfer.sh/qIbbB/init.vim

My issue is I have to invoke the intellisense completion manually by C-x C-o every time. Autopopup only works with buffer words and filesystem paths. I want ncm2 to use the intellisense autopopup.

Ncm2 has no problems with the few LanguageServerClients I've used (F# and Ruby).

And deoplete has no problems with OmniSharp, so I guess I have to do some extra configuring. How do I configure ncm2 to use Omnisharp's completion by default?

**Comment by roxma** [comment]
You could use the css example in the README page as a start for wrapping omnifunc.
