### ISSUE TITLE
Auto-complete mid-word without stutter

### ISSUE THREAD

**Issue by JeanMertz** [ncm2/ncm2#139]
I was unable to find this functionality in the documentation, but I would like this to be possible (`|` is cursor):

```bash
hello_there_world

# current
hello_|world => hello_there_worldworld

# expected
hello_|world => hello_there_world
```

In other words, if I'm mid word, right now it correctly shows completions, but if I use that completion, it does not check if the rest of the word is part of the completion, and omit that part.

Is this currently possible, and if not, would it be a good addition to ncm2?

**Comment by roxma** [comment]
It is not possible currently.

I don't think it's worth adding the complexity. There is the normal command `ce`  to explicitly remove to the end of the word and enter insert mode.
