### ISSUE TITLE
Golang AutoCompletion

### ISSUE THREAD

**Issue by zanven42** [ncm2/ncm2#14]
from #1 i implemented the same setting's of which you had and got the underlying go-langserver setup and working and have found it's gocode auto completion to be lacking. 

do you recommend a specific way to have nice golang support or is it currently not very well supported?

**Comment by roxma** [comment]
You could try port the golang source from ncm to ncm2

Currently I don't have the time porting it.

**Comment by zanven42** [comment]
Yeah ok I will give it a go, should I make my own repo, or prefably would you make an empty repo for me to fork to raise a PR?

**Comment by roxma** [comment]
Feel free to create your own repo

**Comment by roxma** [comment]
You could use https://github.com/ncm2/ncm2-racer as a template if you don't know where to start

**Comment by mfussenegger** [comment]
Are you launching `go-langserver` with  `-gocodecompletion`?

I've it working using `ncm2` with `LanguageClient-neovim` using:

```
let g:LanguageClient_serverCommands.go = [$GOPATH . '/bin/go-langserver', '-gocodecompletion']
```

**Comment by zanven42** [comment]
@mfussenegger i am running with -gocodecompletion, my main issue was i was getting only auto complete for standard packages, i noticed if i have the following typed just now
`custompackage.`

and the cursor is after the dot, if i hit enter in insert mode and press backspace to go back to the dot the autocomplete list starts appearing.

**Comment by roxma** [comment]
https://github.com/ncm2/ncm2-go

**Comment by pratz** [comment]
@roxma thanks mate
