### ISSUE TITLE
Abbreviate items, limit the width

### ISSUE THREAD

**Issue by balta2ar** [ncm2/ncm2#140]
Some of the candidates from tmux source get really huge in the width and are basically useless. However, I need tmux because other candidates from it are useful.
![](https://i.imgur.com/sCBKg4H.png)
Is it possible to abbreviate long candidates somehow, e.g. cut it and put ellipsis in the middle? deoplete does such shortening.
```
Someverylonganddescriptivec...andidate.
```

**Comment by roxma** [comment]
Please test #141

**Comment by balta2ar** [comment]
Thanks, it works! Just two comments, if I may:
1. could you please allow ellipsis symbol customization, e.g. I'd like to use three dots as a single unicode character to save space (or maybe use nothing later, or a kitty emoji, I don't know)
2. could you also make it possible to apply it globally to all sources (on top of their existing filters, of course)? Limit the maximum width globally similarly to `g:ncm2#total_popup_limit`.

**Comment by roxma** [comment]
> 2\. could you also make it possible to apply it globally to all sources (on top of their existing filters, of course)? Limit the maximum width globally similarly to `g:ncm2#total_popup_limit`.

`let g:ncm2#filter = ` applies it to all sources, unless there's `ncm2#override_source('name', {'filter':}` for the source.

**Comment by roxma** [comment]
Use `'ellipsis': '..'` to customize ellipsis text
