### ISSUE TITLE
ncm2_filter set_dup bug removes non duplicates.

### ISSUE THREAD

**Issue by carlevison** [ncm2/ncm2#143]
I am using Intelephense and in my completion popup I have a ```middleware method```and a ```middleware property```

```call ncm2#override_source('intelephense', {'filter': [{'name': 'set_dup', 'value': 0}]})```

the ```middleware method``` is removed from the completion list

**Comment by roxma** [comment]
Not a bug.

The duty of `set_dup` is to set the `dup` field of `:help complete-items`.

**Comment by carlevison** [comment]
Sorry new to vim and setting up my own autocompletion but how can It be a feature to remove a function from the completion list if it isn't a duplicate?

They are separate, they just share the same name where one is a variable and the other is a function.

Could you check the type matches before adding it as a duplicate?

**Comment by carlevison** [comment]
@roxma 

![completion](https://i.imgur.com/swOhrob.png)

By calling ```override_source``` the second from the top is removed as a duplicate when it shouldn't.

**Comment by roxma** [comment]
As mentioned in `:help complete-items`

>        dup             when non-zero this match will be added even when an
>                        item with the same word is already present.

This is vim builtin feature. If you want customized behavior, you could write another filter like https://github.com/ncm2/ncm2/commit/b022eafc43a4811cc218a15d62e4fb6ffcb9e3e7

By the way, you don't need to use `set_dup` if there's no duplication issue.

**Comment by carlevison** [comment]
Thanks for clearing that up but unfortunately i'm not familiar with python.

The language server I am using is using stub files for PHP runtime & extensions header files and that is where I am getting the duplicates from.

**Comment by roxma** [comment]
Please test https://github.com/ncm2/ncm2/pull/145

**Comment by carlevison** [comment]
Working :) thanks again, i'll close this now.
