### ISSUE TITLE
Duplicates come back after sourcing init.vim

### ISSUE THREAD

**Issue by carlevison** [ncm2/ncm2#149]
If I make a change inside my `init.vim` file as soon as source the file after making a change the duplicates come back.

This only happens after sourcing my file, do you know what would be causing this?

I'm on OSX 10.14 and NeoVim 0.3.4

**Comment by roxma** [comment]
I don't think it is a good idea to re-sourcing a complicated complication. Ncm2 is not designed with hot-reload in mind.

Closing...

**Comment by carlevison** [comment]
I didn't know about hot-reload, thanks for the info i'll look into that.
