### ISSUE TITLE
How to have current buffer completions appear first

### ISSUE THREAD

**Issue by carlevison** [ncm2/ncm2#152]
I have registered a php language server with `vim-lsp` and I would like to display everything in the current buffer first in alphabetical order before any completions from outside the buffer. 

Is this currently possible?

**Comment by roxma** [comment]
If the items is already well sorted by the language server, you could disable ncm2's builtin sorting by 
`call ncm2#override_source('source_name', {'sorter': 'none'})`

If you have want customized sorting, you should use [alphanum sorter](https://github.com/ncm2/ncm2/blob/master/pythonx/ncm2_sorter/alphanum.py) as a start and implement your own sorter.

**Comment by carlevison** [comment]
That is exactly what I was looking for, thank you very much.

Could you point me in the right direction on how I would be able to distinguish the current buffer completions from the others so I can try implementing this.

**Comment by roxma** [comment]
I'm not sure there is enough information in the completion item. You may need to [enable logging](https://github.com/roxma/nvim-yarp#debugging) and print some debug log to inspect the items.

**Comment by carlevison** [comment]
I already had debugging setup in Sublime so I checked the server payload and the current buffers completions always has the lowest `uriId`

Is it possible to do to grab the lowest lowest `uriId` and sort them first?

**Comment by roxma** [comment]
The original  lsp completion item from vim-lsp should be in the user_data field: https://github.com/ncm2/ncm2-vim-lsp/blob/7c1cd7c4e5d8aa07f5e7e46e7728fe4b85d373a2/plugin/ncm2_vim_lsp.vim#L100

**Comment by carlevison** [comment]
I'm struggling to setup debugging so I can see what variables are set to, I know in vim script I could use `echom` but seeing what variable a python script is set to has me stumped.

Could you give me a step by step guide on how I could check what content variables currently contain, if I can do that I feel confident I can get this working.

If it helps I am using nvim 0.3.4

Thank you very much for your help, I really appreciate it.

**Comment by carlevison** [comment]
Right now setting sorter to `none` is almost what I want but for some reason setting this option stops `marks` from working.

```
" remove server name from completion popup
call ncm2#override_source('intelephense', {'mark': ''})

call ncm2#override_source('intelephense', {'sorter': 'none'})
```

But now I see `[Intelephense]` in the completion popup. How can I solve this?
