### ISSUE TITLE
Add alternative movement remapping in example

### ISSUE THREAD

**Issue by favetelinguis** [ncm2/ncm2#154]
I would like to use c-j move down c-k move up and c-l select item in the popup list. However im not advanced enough to understand how to do this. Would be nice to add this alternative binding in the readme?

**Comment by Shougo** [comment]
```vim
inoremap <expr><C-j>  pumvisible()?  "\<C-n>" : "\<C-j>"
inoremap <expr><C-k>  pumvisible()?  "\<C-p>" : "\<C-k>"
inoremap <expr><C-l>  pumvisible()?  "\<C-y>" : "\<C-l>"
```
