### ISSUE TITLE
QUESTION: required lines in init.vim

### ISSUE THREAD

**Issue by TylerLeonhardt** [ncm2/ncm2#159]
Hi there,

This is probably a dumb question... but is there a reason `ncm2` or `nvim-yarp` can't include setting:

```vim
" enable ncm2 for all buffers
autocmd BufEnter * call ncm2#enable_for_buffer()

" IMPORTANT: :help Ncm2PopupOpen for more information
set completeopt=noinsert,menuone,noselect
```

with a global setting to overwrite/turn off the behavior?

**Comment by roxma** [comment]
`completeopt` is builtin vim option, It is an important option for completion. I do not want to modify it implicitly. A user familiar with vim should also know what it  does. It cannot be the default for all users. Some may prefer  `set completeopt=noinsert,menuone`. This is what I use in my vimrc:

```vim
set completeopt=noinsert,menuone,noselect
autocmd User Ncm2PopupOpen set completeopt=noinsert,menuone,noselect
autocmd User Ncm2PopupClose set completeopt=menuone
```

`ncm2#enable_for_buffer` is much more easier to understand. If you don't require customization, it's just a single line of config and you know what it does. Why bother keeping it?

I do not use that. This is what I use for better startup time:

```vim
func s:ncm2_start(...)
    if v:vim_did_enter
        call ncm2#enable_for_buffer()
    endif
    autocmd BufEnter * call ncm2#enable_for_buffer()
endfunc

autocmd VimEnter * call timer_start(1000, function('s:ncm2_start'))
```

Some may prefer this version:

```vim
    autocmd InsertEnter * call ncm2#enable_for_buffer()
```
