### ISSUE TITLE
custom match order

### ISSUE THREAD

**Issue by huangyingw** [ncm2/ncm2#160]
when I type in nvim, it will match the file name first then the words in my current buffer.

For example, when I type "he", 
I would expect it to match hello first, for there is already such a word in my current buffer.

While ncm2 prompt me "here.txt", for there is a "here.txt" in the same folder.
Is there a way, to configure ncm2 to match words in my current buffer first, then file/directory name?

**Comment by roxma** [comment]
`call ncm2#override_source('bufword', {'priority': 7})`

**Comment by huangyingw** [comment]
great thanks.
