### ISSUE TITLE
Enabling CSS completion in HTML files

### ISSUE THREAD

**Issue by mangkokoo** [ncm2/ncm2#161]
If you're having trouble with NCM2, Please provide the following information
along with your detailed issue description:

### OS

Elementary OS 5.0 Juno

### neovim `:version` output
`:version                                                                                                                                                     
NVIM v0.3.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-jXFUbD/neovim-0.3.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY
_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -
std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPAC
K_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-jXFUbD/neovim-0.3.4/build/config -I/build/neovim-jXFUbD/neovim-0.3.4/src -I/usr/include -I/build/neovim-jXFUbD/
neovim-0.3.4/build/src/nvim/auto -I/build/neovim-jXFUbD/neovim-0.3.4/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
`

In the plugin description says it can complete CSS/Javascript syntax inside style/script tag. But it  I don't get the sugestion. Only in CSS file works

**Comment by roxma** [comment]
try https://github.com/ncm2/ncm2-html-subscope

**Comment by mangkokoo** [comment]
It works, thank you!
