### ISSUE TITLE
automatically prompt for word in other buffers 

### ISSUE THREAD

**Issue by huangyingw** [ncm2/ncm2#162]
For example, when I type "he". And I have "hello" in my current buffer. 
ncm2 will automatically prompt "hello" to complete.
I really like this.

But, if I type "wo". And I only have "world" in another buffer.
Then ncm2 would not automatically prompt "world", until I press "ctrl + n", then I could see "world" in the prompt list.

How could I change this behavior, so I don't need to press "ctrl + n", and "world", would be automatically prompted ?

**Comment by huangyingw** [comment]
@fgrsnau @roxma
could u help with this issue?

**Comment by fgrsnau** [comment]
I don't think this bug is related to ncm2, as ncm2 does not provide the functionality of completing words in other buffers.

I created an completion source for this: <https://github.com/fgrsnau/ncm-otherbuf>

Do you have this enabled?

**Comment by huangyingw** [comment]
@fgrsnau 
I am trying your plugin, so, the prompt entries with [o], is from your plugin, right ?
great thanks for your work
