### ISSUE TITLE
Any way to make <CR> behave exactly as <C-y> on pum visible?

### ISSUE THREAD

**Issue by edgard** [ncm2/ncm2#163]
Hi! I don't usually use noinsert and unfortunatelly i'm too used to press enter to select the completion.

The problem i'm facing is, if I start typing something and choose the completion with CR, it will complete and enter a newline (with the fix from docs):
inoremap <expr> <CR> (pumvisible() ? "\<C-y>\<CR>" : "\<CR>")

Do you happen to know any way for when the pum is visible AND a I select something to complete with CR, the aditional CR is not done?

Thanks!!!

**Comment by roxma** [comment]
I assume you want `<CR>` when popup menu is open but nothing is selected. You could try this example:

```vim
inoremap <expr> <Plug>(cr_if_no_cmpl) ((!empty(v:completed_item) && !empty(v:completed_item.user_data)) ? "" : "\<cr>")
imap <expr> <CR> (pumvisible() ? "\<c-y>\<Plug>(cr_if_no_cmpl)" : "\<CR>")
```

Note that  the check `!empty(v:completed_item.user_data)` does not work for vim's builtin completion .

Actually it is easier if you have `<up>` and `<down>` mapped to `<c-p>` and `<c-n>`:

```vim
inoremap <expr> <CR> (pumvisible() && !empty(v:completed_item) ? "\<c-y>" : (pumvisible() ? "\<c-y>\<cr>" : "\<CR>"))
```

But usually it is pointless to type an extra `<CR>` to close the popup since the text has already been inserted.

**Comment by edgard** [comment]
Man you are the best. There is exactly what i needed.

Awesome work on the plugin, really really thank you!

**Comment by roxma** [comment]
Here's a more robust version that only do `<CR>` when text stays unchange after `<c-y>`.
```vim
inoremap <expr> <Plug>(cr_prev) execute('let g:_prev_line = getline(".")')
inoremap <expr> <Plug>(cr_do) (g:_prev_line == getline('.') ? "\<cr>" : "\<c-y>")
inoremap <expr> <Plug>(cr_post) execute('unlet g:_prev_line')

imap <expr> <CR> (pumvisible() ? "\<Plug>(cr_prev)\<C-Y>\<Plug>(cr_do)\<Plug>(cr_post)" : "\<CR>")
```

**Comment by edgard** [comment]
This almost works, but its somehow adding a random letter at the end of it, check it out:

https://asciinema.org/a/ppqFylpuoixYy9B59WktJ6cnI

**Comment by roxma** [comment]
Fixed `inoremap <expr> <Plug>(cr_do) (g:_prev_line == getline('.') ? "\<cr>" : "")`

**Comment by edgard** [comment]
Yep! That worked! Awesome, thank you very much!
