### ISSUE TITLE
[Question] Is there any integration with ulti snippets

### ISSUE THREAD

**Issue by rjshrjndrn** [ncm2/ncm2#167]
Hi,

Thank you for this awesome plugin.

One small question.
Is it possible to integrate Ultisnips snippets suggestion?

**Comment by roxma** [comment]
Read https://github.com/ncm2/ncm2/wiki for a list of related resources.

Have you tried this plugin? https://github.com/ncm2/ncm2-ultisnips

**Comment by rjshrjndrn** [comment]
Thank you for your guidance.
