### ISSUE TITLE
[Question] Is there any way to integrate vim-go autocompletion

### ISSUE THREAD

**Issue by rjshrjndrn** [ncm2/ncm2#168]
Hi
Thank you for this awesome plugin. I was trying out vim-go, and found quite interesting. But is there any way to have autocompletion with ncm2 ?

**Comment by rjshrjndrn** [comment]
Sorry to be such a noob. But any thoughts ...

**Comment by roxma** [comment]
Try https://github.com/ncm2/ncm2-go
