### ISSUE TITLE
Feature request - Add neco-look as a completion source

### ISSUE THREAD

**Issue by krishnakumarg1984** [ncm2/ncm2#17]
I use ```vim``` to write prose - in particular latex source, for technical articles such as papers and currently my thesis.

For English language word completion, I use the [```neco-look``` plugin](https://github.com/ujihisa/neco-look). This is supported by deoplete. In fact, this is the only thing that still keeps me with deoplete.

Shall appreciate it if you could add this as a source and tell us how to configure it to work.

**Comment by filipekiss** [comment]
Hey  @krishnakumarg1984! I've took on the challenge and I've got it working:

![untitled](https://user-images.githubusercontent.com/48519/42656561-0748c44e-85f6-11e8-8f68-aeacda42876b.gif)


You can install it using your favorite plugin manager. It's available [here].

Don't hesitate to open an issue if you need anything! :D

[here]: https://github.com/filipekiss/ncm2-look.vim

**Comment by krishnakumarg1984** [comment]
@filipekiss  This is unbelievable. I mean, truly. I am quite bowled over by your enthusiasm and support.  I shall take it out for a spin at the earliest and provide you with a feedback soon.  Many many thanks for this.
