### ISSUE TITLE
centos7  ncm2-go   how can i use it

### ISSUE THREAD

**Issue by omigaZ** [ncm2/ncm2#170]
If you're having trouble with NCM2, Please provide the following information
along with your detailed issue description:

### OS

(If you're using Linux, sharing a reproducible, vimrc minimized docker image,
can definitely help solving the issue)

### Log files if you think the issue is a bug

```sh
export NVIM_PYTHON_LOG_FILE=/tmp/log
export NVIM_PYTHON_LOG_LEVEL=DEBUG
nvim
# reproduce the issue
```

**Comment by omigaZ** [comment]
i use nvim  and vim-plug     bug  it not works

**Comment by roxma** [comment]
Make sure that `https://github.com/mdempsky/gocode` is installed and `gocode` binary is available in your `PATH`.
