### ISSUE TITLE
Resetting completeopt deletes characters

### ISSUE THREAD

**Issue by dlukes** [ncm2/ncm2#174]
When I configure `completeopt` resetting as described in `:help Ncm2PopupOpen`, the action of showing/hiding the popup leads to some characters being deleted. The examples below use `pyls` via [autozimu/LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) as the completion source.

In the following, I have to type `str.ll` in order for `str.l` to show up on the screen, i.e. the first `l` I type is eaten up in the process of showing the `ncm2` popup:

![no_autopairs](https://user-images.githubusercontent.com/2734517/69864361-0919b080-129f-11ea-8106-9c1d6a0a9335.gif)

The issue is more conspicuous when the [jiangmiao/auto-pairs](https://github.com/jiangmiao/auto-pairs) plugin is added to the mix -- here, I type `str.llower().`, but I end up with `str.lower`, i.e. the final period plus the parens get erased (in addition to the first `l`, as before):

![with_autopairs](https://user-images.githubusercontent.com/2734517/69864484-4e3de280-129f-11ea-8955-2e4198636997.gif)

If I disable dynamic `completeopt` resetting and just statically `set completeopt=noinsert,menuone,noselect`, I get the desired behavior, even with `auto-pairs` enabled, i.e. when I type `str.lower().`, the same thing actually shows up in the buffer:

![no_completeopt_reset](https://user-images.githubusercontent.com/2734517/69864816-12efe380-12a0-11ea-9279-dc460ee48df8.gif)

I'm pretty sure this didn't use to be the case, I write Python fairly often and my setup hasn't changed recently in this regard. I updated my plugins and then noticed these deletions happening. To work around the one in the second gif, I have to exit and re-enter insert mode, which is enough friction that I'm confident I would've noticed if it'd been happening before.

Let me know if I can be of more help, and thanks for a great plugin! :)

### OS

macOS 10.15.1, Solus 4.0 (Linux)

### neovim `:version` output

```
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_
GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include
-I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-9a287301-34f2-4b86-92e3-462594f51f36

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

### Minimal vimrc for reproducing the issue

As is, this vimrc reproduces the issue as shown in the first gif. See `NOTE:` comments for how to reproduce the other two gifs.

```vim
" test_vimrc
set nocompatible
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath

call plug#begin()
" NOTE: the issue is easier to see with auto-pairs enabled, cf. second
" gif
" Plug 'jiangmiao/auto-pairs'
Plug 'roxma/nvim-yarp'
Plug 'ncm2/ncm2'
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
call plug#end()

autocmd BufEnter * call ncm2#enable_for_buffer()

" NOTE: if I disable the following four lines...
let s:completeopt_default = 'longest,menuone'
let &completeopt = s:completeopt_default
autocmd User Ncm2PopupOpen set completeopt=noinsert,menuone,noselect
autocmd User Ncm2PopupClose let &completeopt = s:completeopt_default

" NOTE: ... and enable the one below, i.e. if I set completeopt just
" once and leave it alone, the issue goes away, even with auto-pairs
" enabled (cf. last gif)
" set completeopt=noinsert,menuone,noselect

let g:LanguageClient_serverCommands = { 'python': ['pyls'] }
```

### Versions of other components

Python language server:

```
pip3 install python-language-server==0.31.1
```

Output of `PlugSnapshot`:

```vim
" Generated by vim-plug
" Fri 29 Nov 2019 11:42:25 AM CET
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['LanguageClient-neovim'].commit = 'a7d3456'
silent! let g:plugs['auto-pairs'].commit = '39f06b8'
silent! let g:plugs['ncm2'].commit = '160e2e3'
silent! let g:plugs['nvim-yarp'].commit = '83c6f4e'

PlugUpdate!
```

### neovim `:messages` output when the error occurs

Nothing interesting, just:

```
[LC] Project root: /home/david/Nextcloud
```

### Log files if you think the issue is a bug

These log files correspond to the issue as demonstrated in its more conspicuous form in the second gif.

[logs.zip](https://github.com/ncm2/ncm2/files/3904882/logs.zip)

**Comment by dlukes** [comment]
Also, please let me know if you think this is not an issue that can be solved on `ncm2`'s side but has to be solved at the level of one of the other components involved, in that case I'll try to file an issue there :)

**Comment by dlukes** [comment]
I've done some digging and is it possible that the `s:startbcol` variable in `ncm2.vim` isn't getting updated properly? It looks like when I come to the point when I've typed `str.lower().`, a completion gets triggered with `s:startbcol` set to 5, which if I understand it correctly, tries to complete at the previous completion point `str.` (i.e. starting from the 5th column), instead of at `str.lower().`, which is how the text gets erased.

**Comment by dlukes** [comment]
Did a `git bisect` and 3c48d430e69a84cb2d89dadc43008576ea0063bf is the first bad commit.

**Comment by roxma** [comment]
Please test #175

**Comment by roxma** [comment]
BTW, this is the most informative issue report I've seen. Thanks.

**Comment by dlukes** [comment]
> Please test #175

As far as I can see, this works great, thank you!

> BTW, this is the most informative issue report I've seen. Thanks.

Well it's the least I could do, I'm grateful you spend some of your time on ncm2 et al. and share the fruits of that labor with the rest of us :) I thought I might be able to come up with a fix, but unfortunately, it turns out there are too many moving parts that I know too little about, especially how the editor itself behaves.
