### ISSUE TITLE
nvim-lsp: completion throws error

### ISSUE THREAD

**Issue by Kyle-Thompson** [ncm2/ncm2#180]
Using neovim nightly's LSP I'm given an error whenever ncm2 tries to create a completion pum.

### OS
Arch Linux

### neovim `:version` output
NVIM v0.5.0-404-g49cd750d6

### Minimal vimrc for reproducing the issue
```
set packpath=~/.config/nvim/
packadd nvim-yarp
packadd nvim-lsp
packadd ncm2
autocmd BufEnter * call ncm2#enable_for_buffer()

lua << EOF
local nvim_lsp = require('nvim_lsp')
local ncm2 = require('ncm2')
nvim_lsp.clangd.setup{on_init = ncm2.register_lsp_source}
EOF
```

### neovim `:messages` output when the error occurs
Error executing vim.schedule lua callback: shared.lua:468: prefix: expected string, got nil
Error executing vim.schedule lua callback: shared.lua:468: prefix: expected string, got nil

**Comment by Anexen** [comment]
Hi, please see https://github.com/ncm2/ncm2/pull/181
