### ISSUE TITLE
Ultisnips support with nvim-lsp

### ISSUE THREAD

**Issue by Kyle-Thompson** [ncm2/ncm2#182]
As mentioned in https://github.com/ncm2/ncm2/pull/178#issuecomment-583714029 there doesn't seem to be any support for snippets with the new built in LSP client. Has anyone had success with this? If so, what config options are needed?

**Comment by megalithic** [comment]
echoing a desire for this.

**Comment by Anexen** [comment]
Could you please share a minimal reproducible `vimrc`? I tried the following and it works as expected:

```
call plug#begin('~/.config/nvim_ncm2/plugged')

Plug 'roxma/nvim-yarp'
Plug 'Anexen/ncm2', {'branch': 'fix/built-in-lsp'}
Plug 'ncm2/ncm2-ultisnips'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'neovim/nvim-lsp'

call plug#end()

autocmd BufEnter * call ncm2#enable_for_buffer()

set completeopt=noinsert,menuone,noselect

let g:UltiSnipsEditSplit = 'context'

inoremap <silent> <expr> <CR> ncm2_ultisnips#expand_or("\<CR>", 'n')

lua << EOF
local nvim_lsp = require('nvim_lsp')
local ncm2 = require('ncm2')
nvim_lsp.pyls.setup{on_init = ncm2.register_lsp_source}
EOF

```

I have the latest versions of plugins and nvim version v0.5.0-404-g49cd750d6

![nvim-snippets](https://user-images.githubusercontent.com/5568591/75817453-28e1d880-5da8-11ea-9ce9-14076d4cfb37.gif)

**Comment by Kyle-Thompson** [comment]
Here is the minimal vimrc to reproduce. Note that with the exception of the plugin manager, it is the same as yours as far as I can tell. I've also included the exact git hashes for each commit I used. This was immediately after updating each one.

```
set packpath=~/.config/nvim/

packadd nvim-yarp       " 83c6f4e
packadd ncm2            " eea3897
packadd ncm2-ultisnips  " a7462f3
packadd ultisnips       " e910b4f
packadd vim-snippets    " 28ad634
packadd nvim-lsp        " 3bcc387

autocmd BufEnter * call ncm2#enable_for_buffer()
set completeopt=noinsert,menuone,noselect
let g:UltiSnipsEditSplit = 'context'
inoremap <silent> <expr> <CR> ncm2_ultisnips#expand_or("\<CR>", 'n')

lua << EOF
local nvim_lsp = require('nvim_lsp')
local ncm2 = require('ncm2')
nvim_lsp.clangd.setup{on_init = ncm2.register_lsp_source}
EOF

set packpath=
```

The exact steps to reproduce:
1. type a name in scope and hit dot
2. use <C-n> to iterate through the pum to the function
3. hit enter to expand the snippet.

The behavior instead of expanding the function snippet is that it instead acts as if I had just hit enter normally, giving me a carriage return. Given how similar our configs are, I'm tempted to believe this is caused by the way I'm trying to expand the snippet which is curious since this way has worked for me before.

**Comment by Kyle-Thompson** [comment]
Also I just noticed, your use of snippets wasn't expanding any prompts given to you by the LSP. Opening a class snippet I'd imagine doesn't involve any communication with the LSP but expanding a snippet like `foo(int a, bool b)` from c++ will involve some kind of interaction with the LSP. Can you confirm if this kind of snippet expansion also works for you or is it just expanding built in snippets like `class`?

**Comment by Kyle-Thompson** [comment]
Okay so I just tested this myself and I can confirm that with both my regular and minimal setup I can properly expand snippets given my `vim-snippets`. The real issue is expanding snippets given by the LSP. An example of that is shown in the original comment that I linked above.

**Comment by Anexen** [comment]
@Kyle-Thompson, yes, you are right. 

Seems like snippets are not supported by built-in LSP client:

- https://github.com/neovim/neovim/issues/11982
- https://github.com/neovim/neovim/pull/11949

**Comment by onyx-tools** [comment]
Well I suppose this can be closed then while we wait for official support.

**Comment by Kyle-Thompson** [comment]
Well I guess this can be closed then while we wait for official support.

**Comment by archseer** [comment]
Preliminary support here https://github.com/ncm2/ncm2_lsp_snippet/pull/1
