### ISSUE TITLE
How to hide function-parameters popup?

### ISSUE THREAD

**Issue by subnut** [ncm2/ncm2#190]
This is when I am typing the function (i.e. auto-completion)
![ncm2_report1](https://user-images.githubusercontent.com/56714626/88846874-dd6f1180-d203-11ea-887e-c900a95ed1cc.png)

And this is when autocompletion is finished. i.e. it is the popup showing the function definition/parameters:
![ncm2_report](https://user-images.githubusercontent.com/56714626/88846964-ff689400-d203-11ea-832d-6f367ba62392.png)

I want to hide the second one, but still show the first one. How?

**Comment by roxma** [comment]
This is an issue of https://github.com/ncm2/ncm2-jedi
We could add an option to disable function-parameters popup

**Comment by roxma** [comment]
Use `let g:ncm2_jedi#call_sig_hint = 0`
