### ISSUE TITLE
Custom key for filtering (matcher_key)

### ISSUE THREAD

**Issue by balta2ar** [ncm2/ncm2#21]
Hi. I'd like to give ncm2 a try, but it appears that I'm stuck with deoplete because of its very convenient `matcher_key` feature that I use in some of my sources:
issue: https://github.com/Shougo/deoplete.nvim/issues/759
implementation: https://github.com/Shougo/deoplete.nvim/commit/1cacfeb561fc65c3301c9771480c89064fcb8940
sample usage: https://gist.github.com/balta2ar/2f06ae40f8d7addf0bd501dd0a2411d9

Is possible to implemented similar functionality here? Thank you.

**Comment by roxma** [comment]
Ncm2 support matcher per source. I'm not sure that would solve your issue.

https://github.com/ncm2/ncm2/blob/master/pythonx/ncm2_matcher/prefix.py

A matcher could be implemented as simple as

```python
class Matcher:
    def match(self, b, m):
        lb = len(b)
        w = m['word'][ : lb]
        if b != w:
            return False
        return True
```

In the matcher, you have full access of the   `:help complete-item`, which is the arg `m` in this case. You could do any filtering you want for custom source.

**Comment by balta2ar** [comment]
Sure, that's what I did in my source before matcher_key was added. But the reasoning was that it could be a convenient and frequent pattern that was worth implementing in the core. OK, I'll get back to you when I have it implemented.

**Comment by roxma** [comment]
I have added match key support for matchers, 

Try something like this with [abbrfuzzy](https://github.com/ncm2/ncm2-abbrfuzzy)

```vim
let g:ncm2_jedi#source.matcher = {'name':'abbrfuzzy', 'args': ['smartcase', 'menu']}
```

![rec](https://user-images.githubusercontent.com/4538941/42695412-e1a45558-86e7-11e8-8bad-3651640270a1.gif)

**Comment by roxma** [comment]
hmm... This doesn't seem convenient to me.

I'm going to change the matcher interface...

**Comment by roxma** [comment]
For overriding sources options:

```vim
let g:ncm2_jedi#source_override = {'matcher': {'key': 'menu'}}
" thils will override g:ncm2_jedi#source when initializing
```

When registering custom source, add a `matcher` option: `'matcher': {'key': 'menu'}`

**Comment by balta2ar** [comment]
I've just given it a try to port my source from deoplete to ncm2, and it was a breeze! No effort whatsoever, and the basic functionality is working just fine. I'll have to live with it for a while to make sure there are no rough edges left. Below is my feedback, if you're interested:

1) One thing that I loved in deoplete is that I could write my source in Python only. Here I have to boilerplate some minimal amount of vimscript code. Given the fact that I have no experience with vimscript (and I know it's my problem, I should have studied the instrument that I'm using), the deoplete approach is still more appealing to me. If I could create sources and configure them only in Python, it could be really great and simple.

2) I've tried `abbrfuzzy` and it's wonderful! But sometimes I'm just not sure whether I remember the correct beginning of a word... Would it be possible to add even more fuzzier matcher here, e.g. cpsm matcher as in deoplete? I've been using it in deoplete source for a long while and it's been working great.

3) Instead of `menu` I'm using `custom` field. When I used `menu`, it displayed in the completion menu basically duplicating information about candidates. This is not really a feedback, just my findings that could be useful to someone who discovers this issue and follows my tracks.

**Comment by roxma** [comment]
> . Would it be possible to add even more fuzzier matcher here,

It is possible.

But I havent' look into others implementations.

There's used to be a fuzzy matcher in old ncm. I didn't like it. I often got matches I don't want.

Current abbrfuzzy is almost perfect for me.

> I'll probably need fuzzy search for my URL source that completes URLs from browser tabs.

In case abbr based fuzzy match doesn't work so well, you could also try a combination of substr matcher, enabled by this PR: https://github.com/ncm2/ncm2/pull/23
