### ISSUE TITLE
Install instruction

### ISSUE THREAD

**Issue by huyvohcmc** [ncm2/ncm2#24]
1. Why don't we put `autocmd BufEnter * call ncm2#enable_for_buffer()` to the plugin itself?
2. In my machine (macbook pro 10.13.5, nvim 0.3, python2.7.15 and python3.7), you need to `set completeopt=noinsert,menuone,noselect` in order to get the completion popup while the README says `menuone` and `noselect` are optional.

**Comment by roxma** [comment]
> Why don't we put autocmd BufEnter * call ncm2#enable_for_buffer() to the plugin itself?

- Calling `ncm2#enable_for_buffer()`  will evantually invoking neovim's remote python host, which is kinda heavy for startup. I prefer to use a delayed startup on my own vimrc. But delayed startup has its own issue when you want to open nvim and edit really fast, I don't want to decide this behavior for eveoryone.
- There're buffers you might not want ncm2 enabled, e.g. a buffer that is too large, or a special buffer created by other plugins.

I cannot generalize ncm2 to fit all buffers, and for all vimrc setup. I don't want to get ncm2 too complicated either.

A better approach is that you understand what the vimrc is doing, and evantually you're gonna tune it to fit your own need in the long term.

>  says `menuone` and `noselect` are optional

They are optional. You need to read `:help completeopt` to understand its behavior.
