### ISSUE TITLE
Set 'abbr' to empty string if not set

### ISSUE THREAD

**Issue by clason** [ncm2/ncm2#26]
While setting up the new `combine` matcher (which is great, thanks!) for vimtex, I noticed that ncm2 initializes the `abbr` field to `word` in https://github.com/ncm2/ncm2/blob/master/pythonx/ncm2.py#L85. Is there a specific reason for this? This prevents me from matching `word` more strictly than `abbr`; for this purpose,
```
 if 'abbr' not in e or type(e['abbr']) != str:
            e['abbr'] = ''
```
would be needed. (This would also be more consistent with the other fields.)

**Comment by clason** [comment]
Ah, so for ncm2 `abbr` is more fundamental than `word` -- from `:h complete-items`, it seemed the other way arround: 

>       abbr            abbreviation of "word"; when not empty it is used in
>                       the menu instead of "word"

This sounded like an empty `abbr` is the default, and in my test the change I mentioned above does work exactly as I need, but of course I always only have a single (`omnifunc`) source.

Unless I misunderstand, your suggestion doesn't really help here, since I want to *remove* something from the results, which ncm2 will then re-add anyway? Is there any way to match on `abbr` *only* when it is different from `word`?

**Comment by roxma** [comment]
> Unless I misunderstand, your suggestion doesn't really help here, since I want to remove something from the results, which ncm2 will then re-add anyway?

You could wrap the `omnifunc` and create extra fields,

```
item.orig_abbr = get(item, 'abbr', '')
```

And then you could use a matcher to filter on `orig_abbr`.

There're ways to do this. You could even wrap `ncm2_core.match_formalize`, just like how `ncm2-match-highlith` does. Though this is not recommended, since the undocumented part is more likely to change.

**Comment by clason** [comment]
I see, yes, this makes sense. Actually, I think I see now how to do this with multiple ncm2 sources that call `omnifunc` with different matchers based on the context.

Sorry for spamming so many issues and comments -- I do appreciate your time answering them, which has been quite helpful!

**Comment by clason** [comment]
Hmm, no, that doesn't quite seem to work. I might have gotten the regexp wrong, but in principle I should be able to register two different sources that complete depending on the regexp, e.g., the first one triggers on matching (for simplicity) `\\[A-Za-z]*[^{]$` (so for `\cit` but not `\cite{`) and the other one on matching `\\cite{*` (so vice versa)?

**Comment by roxma** [comment]
There's no need to use `$` in `complete_pattern`.

NCM2 cache completion results based on `word_pattern`.  which means `\cite{sometext|` will also trigger completion for `{` if there's no cache for the source.

See https://github.com/ncm2/ncm2/blob/master/pythonx/ncm2_core.py#L412 for how `complete_pattern` actually works

**Comment by clason** [comment]
Right, I see (sorry for the off-the cuff regexp). Using `word_pattern` kind of works, but I have problems with the wrong regexp triggering when it shouldn't -- but only if it's in a list (`'word_pattern': 'regexp'` works correctly, but `'word_pattern': ['regexp']` doesn't). Is this a bug for which I should open an issue, or am I doing something wrong?

**Comment by roxma** [comment]
`word_pattern` is not a list.

There's a few examples in the doc. (`:help ncm2#register_source`) They might help you understand how thoes patterns work.

```
        complete_length: 3
        complete_pattern: ['\.']
        word_pattern: '\w+'

            typing            : foo_service.request()
            complete trigger  :   ^        ^
            startccol         : x           x
            base              : [.........] [.....]

            typing            : fd.read()
            complete trigger  :   ^
            complete trigger  :    x
            base              :    [..]

        complete_length: -1
        complete_pattern: ['/']
        word_pattern: '\S+'

            typing           : first/second/third
            complete trigger :      ^      ^
            startccol        : x
            base             : [................]
```

**Comment by clason** [comment]
Oh, I see, then I misunderstood this. So if I want to trigger a certain source based on a (list of) regexp patterns, that's currently not possible?

**Comment by clason** [comment]
Ah, now I get it! It's the `complete_length` that was the problem -- this controls completion *independently* of the `complete_pattern`. So if I set it to `1` (which I did based on https://www.reddit.com/r/vim/comments/8ws2kl/nvimcompletionmanager_is_now_ncm2/e27nt9k), it overrode the regexp.  Setting it to `-1` instead (or leaving it completely -- or does that have other side effects?) makes everything behave as I want.

Thank you so much for your help and patience! (And sorry for not reading the documentation in more detail; now that I know what the issue is, I can see that it's already explained there...)

**Comment by roxma** [comment]
Set `complete_length` to -1 if you want to control the completion trigger explicitly by `complete_pattern`.

Leaving it empty will be defaulted by the framework using `:help g:ncm2#complete_length`

**Comment by clason** [comment]
Understood. Last question, while we're at it, since I'll be adding this to the vimtex documentation: What would you recommend for the priorities here?

**Comment by roxma** [comment]
I'm not familiar with latex. But in general, If vimtex is the smartest completion engine available for latex files, it should be 9. If you have better options for latex files, set it to lower priority.

**Comment by clason** [comment]
It will be until someone creates `ncm2-tex` and `ncm2-bibtex` 😄  I'll set it to `8` for now. Thank you for all your help! I'm really happy with ncm2 so far!

**Comment by roxma** [comment]
FWIW, I've replace the boring pure text explanation with a more interactive script example. https://github.com/ncm2/ncm2/commit/0bf906b76636dc6ac5635660e884229138b8608d

It should be way more helpful for debugging and understand how ncm2 works.

**Comment by balta2ar** [comment]
> I've replaced the boring pure text explanation

Could you please leave both? I actually liked it, and it helped me understand the difference between complete_pattern and word_pattern...

**Comment by roxma** [comment]
Ok, now both versions are available.
