### ISSUE TITLE
[RFC] more fuzzy matcher

### ISSUE THREAD

**Issue by roxma** [ncm2/ncm2#30]
As per https://github.com/ncm2/ncm2/issues/21

However, pure fuzzy match may not be a good idea.

Here's a proposal:

For candidate like `HelloWorld`, split it into `Hello` and `World`,

We only allow substr match in `Hello`, and `World`, 

So `ellold` should match `ell` in `Hello`, `rld` in `World`.

But with `eoworld`  , `eo` shouldn't match `Hello`. So  it should not match `HelloWorld`

I'm not sure what  sort priority is better. It seems the abbrfuzzy still works for this proposal.

// cc @balta2ar

**Comment by balta2ar** [comment]
What you describe sounds reasonable. Another aspect that I'd like to add here is that in abbrfuzzy the order of the words matters, in a query the user has to specify them left to right. However, sometimes I remember just key words from the title in no particular order. Consider my typical candidates (https://github.com/Shougo/deoplete.nvim/issues/759):
```
OFFICE_IT-1257  Fix hg hook in cs/rnd-tests repo        Resolved        user1   2018-02-27
IT_SUPPORT-236  Configure certificates on https://someurl.company.net   Resolved        user2   2018-03-02
IT_DEV-319      Hypertext links to Crucible reviews in RT comments      On Hold <NA>    2018-03-12
GENERAL-1874    Re: changes for 2018 (high level summary)       New     <NA>    2018-03-10
DEMO-56 my test Open    user3   2018-03-06
ACCESS-6092     Please create bot user for SecretProject <-> TopSecretProject interaction       Resolved        user4   2018-03-05
ACCESS-2432     wrong permissions in test project. user1        Resolved        user1   2018-02-27
```
Here, `word` is the first column, `abbr` is the second (or vice versa... sorry, I always confuse them but it doesn't matter).

Consider the third line:
```
IT_DEV-319      Hypertext links to Crucible reviews in RT comments      On Hold <NA>    2018-03-12
```

In a perfect scenario I'd like the following query to rank that line first:
```
JIcrutext
```
`JI` -- it just a prefix that is added to all candidates to trigger the source, `cru` is Crucible, `text` is Hypertext. Notice that in the candidates Hypertext goes before Crucible, and the order is reversed in the query.

I'm not sure how computationally feasible this problem is, so maybe it's not worth it. `abbrfuzzy` and `libcpsm` (from my experience with deoplete) indeed do a good job most of the time here.

**Comment by fcying** [comment]
add a matcher like deoplete `matcher_fuzzy`?
Abbrfuzzy which now used, if not have `-`, it can't match fuzzy.
ex:
```
os.getuid
```
type `os.uid` can't get any complete.

**Comment by roxma** [comment]
@fcying 

You could try this config for now:

```vim
    let g:ncm2#matcher = {
                \ 'name': 'combine',
                \ 'matchers': ['abbrfuzzy', 'substr']
                \ }
```

**Comment by fcying** [comment]
It can work, thanks~

**Comment by roxma** [comment]
`let g:ncm2#matcher = 'substrfuzzy'`

This implementation looks fine. 

I still need some feedback.

**Comment by roxma** [comment]
Test case, the last example does not look so nice, though.

```
$ python3 pythonx/ncm2_matcher/substrfuzzy.py
base : subfuzzy
str  : substr_fuzzy_match
split: ^      ^     ^
       substr_fuzzy_match
match: ^^^    ^^^^^

base : substrfuzzy
str  : substr_substrfuzzy_match
split: ^      ^           ^
       substr_substrfuzzy_match
match:        ^^^^^^^^^^^

base : sfum
str  : substr_substrfuzzy_match
split: ^      ^           ^
       substr_substrfuzzy_match
match: ^            ^^    ^

base : abcfoo
str  : abc_foo_abcf
split: ^   ^   ^
       abc_foo_abcf
match: ^^^ ^^^

base : abcfoo
str  : a_b_c_abc_abfoo
split: ^ ^ ^ ^   ^
       a_b_c_abc_abfoo
match: ^ ^ ^       ^^^
```

**Comment by roxma** [comment]
I have improved `substrfuzzy`. The results looks better now.

```
roxma-pc ncm2 $ python3 pythonx/ncm2_matcher/substrfuzzy.py
base : subfuzzy
split: |      |     |
str  : substr_fuzzy_match
match: ^^^    ^^^^^

base : substrfuzzy
split: |      |           |
str  : substr_substrfuzzy_match
match:        ^^^^^^^^^^^

base : sfum
split: |      |           |
str  : substr_substrfuzzy_match
match: ^            ^^    ^

base : sfuym
split: |      |           |
str  : substr_substrfuzzy_match
match: ------------------------

base : abcfoo
split: |   |   |
str  : abc_foo_abcf
match: ^^^ ^^^

base : abcfoo
split: | | | |   |
str  : a_b_c_abc_abfoo
match:       ^^^   ^^^
```

**Comment by balta2ar** [comment]
Thank you! Because I have only one plugin that is likely to require fuzzy matching, I enabled it only there and I'll see how it goes.
```vim
let g:ncm2_jira#source = get(g:, 'ncm2_jira#jira_source', {
            \ 'name': 'jira',
            \ 'priority': 9,
            \ 'mark': 'jira',
            \ 'word_pattern': 'JI\w*',
            \ 'complete_pattern': 'JI\w*',
            \ 'matcher': {'key': 'custom', 'name': 'substrfuzzy'},
            \ 'on_complete': 'ncm2_jira#on_complete',
            \ 'on_warmup': 'ncm2_jira#on_warmup'
            \ })
```
