### ISSUE TITLE
typescript completion with tsuquyomi#complete omnifunc wrap failed

### ISSUE THREAD

**Issue by isczg** [ncm2/ncm2#33]
Since ncm2 hasn't come up with typescript extension yet, I tried the omnifunc wrap with [Quramy/tsuquyomi](https://github.com/Quramy/tsuquyomi) which provided the ts omnifunc. It didn't work: the completion popup didn't appear, using "c-x c-o" can call up the completion successfully, though.

### OS
windows 10

### neovim `:version` output
NVIM v0.3.0
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv -jemalloc +tui 
See ":help feature-compile"

### Minimal vimrc for reproducing the issue
filetype off
call plug#begin('~/AppData/Local/nvim/plugged')
Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
Plug 'Shougo/vimproc.vim', {'do' : 'make'}
Plug 'Quramy/tsuquyomi'
Plug 'leafgarland/typescript-vim'
Plug 'HerringtonDarkholme/yats.vim'
call plug#end()
filetype plugin indent on
syntax on

autocmd BufEnter * call ncm2#enable_for_buffer()
set completeopt=noinsert,menuone,noselect

call ncm2#register_source({
          \ 'name' : 'typescript',
          \ 'priority': 9, 
          \ 'subscope_enable': 1,
          \ 'scope': ['typescript'],
          \ 'mark': 'ts',
          \ 'word_pattern': '\w+',
          \ 'complete_pattern': '\\.',
          \ 'on_complete': ['ncm2#on_complete#omni', 'tsuquyomi#complete'],
          \ })

### neovim `:messages` output when the error occurs
[ncm2_core@yarp] typescript on_complete: Vim(let):E716: Key not present in Dictionary: 0

**Comment by roxma** [comment]
Two causes at least:

- The omni wrapper is impossible to work with an omnifunc that calls `complete_add`
- Unknown edge case. Need more time to dig into its source code.

A better alternative is to try port nvim-typescript source. I did it for old ncm before. https://github.com/mhartington/nvim-typescript/pull/81
https://github.com/mhartington/nvim-typescript/commit/92e26d2e4c2eb9f7b6569d661cdc40bfc426676f
