### ISSUE TITLE
Set limit to the number of candidates for a source

### ISSUE THREAD

**Issue by balta2ar** [ncm2/ncm2#38]
Hello! Could you please add a feature to forcefully limit the number of candidates from a source? For example, `look` and `tmux` sources sometimes give out just way too many candidates, and I'd like to see other options as well. As an example, I had these settings for deoplete:
```vim
call deoplete#custom#source('look', 'max_candidates', 5)
call deoplete#custom#source('webcomplete', 'max_candidates', 5)
call deoplete#custom#source('tmux-complete', 'max_candidates', 5)
call deoplete#custom#source('buffer', 'max_candidates', 5)
```

**Comment by roxma** [comment]
Why not `set pum_height`?

**Comment by balta2ar** [comment]
As far as I understand, it will limit the total height of the menu. This means if `look` source floods the menu with candidates, I won't see candidates from other sources with lower priority. Ideally, I'd like to see candidates from several sources at once.

**Comment by balta2ar** [comment]
I have several more-or-less equally low priority sources such as look, tmux, web, and one of them usually takes all the space, leaving no room for others.
