### ISSUE TITLE
What is setting the font style in Pmenu?

### ISSUE THREAD

**Issue by docwhat** [ncm2/ncm2#40]
NVIM v0.3.1
Build type: Release
iTerm2

What's causing this weird outline-ish font for the typed part of the match in the Pmenu?  In the screen shot below it is the `num` part of the match.

![image](https://user-images.githubusercontent.com/40799/43207270-b2b94ab6-8ff5-11e8-8293-58d6dc0f2a08.png)

I don't think this is necessarily NCM's fault. I see it in the [readme](https://github.com/ncm2/ncm2#readme) as well, so whomever created that animated screenshot has the same effect as well.

Thanks!

**Comment by roxma** [comment]
https://github.com/ncm2/ncm2-match-highlight

**Comment by docwhat** [comment]
Things I've ruled out:

- It isn't iTerm vs Terminal.
- It isn't the `gruvbox` theme.
- It isn't Neovim 0.3.1; it's in 0.2.2 as well.

**Comment by docwhat** [comment]
@roxma  Thank you very much.  Hopefully this will help people in the future.
