### ISSUE TITLE
Question about LangServer and language plugins

### ISSUE THREAD

**Issue by asymmetric** [ncm2/ncm2#41]
Hi, thanks a lot for your efforts on ncm and ncm2!

Not sure if I understand things correctly, but: if I only configure the `LanguageClient-neovim` plugin in addition to ncm2, I will get support for all languages for which I have a language server - correct?

Considering e.g. Rust has the RLS, and that RLS uses racer as its source, what's the point of `ncm2/ncm2-racer`?

Same goes with the other language-specific plugins: what's the point, if there are language servers for them?

Thanks!

**Comment by roxma** [comment]
- All I need for my daily work are just decent completion and goto declaration support
- It's way easier for me to setup and debug small and scriptable vim/nvim plugins than language servers
- It's still nice to have choices. I don't want to rule everything with language servers.
- I use neovim only. It's pointless for me to be cross-editor-compatible. There're existing  simple tools to create language plugins.

**Comment by z-huabao** [comment]
@roxma 
Hi, thank for your works, I use jedi-vim before, try `ncm2` and `ncm2-jedi` now, but I don't know how to goto declaration(for Python)? and it seems `LanguageClient-neovim` can do it?

**Comment by roxma** [comment]
@z-huabao  You could still use `jedi-vim` for goto declaration.

**Comment by z-huabao** [comment]
Thanks, done it, jedi-vim work well
