### ISSUE TITLE
ncm2 inserts text when entering search before initializing

### ISSUE THREAD

**Issue by davidosomething** [ncm2/ncm2#47]
using `  autocmd BufEnter * call ncm2#enable_for_buffer()`

start vim and immediately enter `/` to start searching

![screen recording 2018-07-31 at 05 34 pm](https://user-images.githubusercontent.com/609213/43488552-2717b2ca-94e8-11e8-851b-98638cccdeb3.gif)

I am using the following search plugins

```
  Plug 'haya14busa/vim-asterisk'
  Plug 'haya14busa/incsearch.vim', PlugIf(v:version >= 704)
  Plug 'osyo-manga/vim-anzu'
```

in neovim 3

**Comment by roxma** [comment]
Have you updated to the latest version?

Possibly duplicate: https://github.com/ncm2/ncm2/issues/42

**Comment by roxma** [comment]
I cannot reproduce this issue

**Comment by davidosomething** [comment]
incsearch.vim with incsearch-forward mapping is the issue since it messes with insertmode and commandline behavior

disabled incsearch.vim for now

**Comment by roxma** [comment]
You could try `call ncm2#lock(why)` and `call ncm2#unlock(why)` before and after.
