### ISSUE TITLE
Strange folds behavior

### ISSUE THREAD

**Issue by xdefrag** [ncm2/ncm2#53]
I don't know how it all tied up, but after installing ncm2 vim feels sluggish and all folds constantly reloads after every swap file write. 

### OS
Arch Linux 4.17.12

### neovim `:version` output
```vim
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMI
N_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-
protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FL
OAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.1/src -I/usr/include -I/build/ne
ovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Minimal vimrc for reproducing the issue
```vim
call plug#begin('~/.cache/nvim/plugins')
Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
call plug#end()

set updatetime=200

autocmd BufEnter * call ncm2#enable_for_buffer()

" Example {{{
" BODY
" }}}
" vim:foldmethod=marker:foldlevel=0
```

### neovim `:messages` output when the error occurs
empty

### Log files if you think the issue is a bug
[py3_ncm2_core.log](https://github.com/ncm2/ncm2/files/2266186/py3_ncm2_core.log)
[py3_script.log](https://github.com/ncm2/ncm2/files/2266187/py3_script.log)

[![asciicast](https://asciinema.org/a/9rdrJ8a5kJ2ugzBlJO7kJNc9C.png)](https://asciinema.org/a/9rdrJ8a5kJ2ugzBlJO7kJNc9C)

**Comment by zeroqn** [comment]
Add "<nomodeline>" to all "doau" expressions in autoload/ncm2.vim should fix this problem.

**Comment by roxma** [comment]
@zeroqn 

Thanks. Would you explain why that will fixes the issue?

**Comment by zeroqn** [comment]
According to \<nomodeline\> document.

> After applying the autocommands the modelines are processed, so that their settings overrule the
settings from autocommands.

This means the folds will be "reset" in this case.
