### ISSUE TITLE
Implementation of dictionary completion plugin

### ISSUE THREAD

**Issue by yuki-ycino** [ncm2/ncm2#55]
I mainly use vim 's dictionary completion when writing LL.
Since dictionary complement plug-in was not found in ncm 2, I implemented it myself simply.

Because I am not used to writing in python, I have done synchronous implementation of vim script. I'm sorry.

The repository is https://github.com/yuki-ycino/ncm2-dictionary
If someone is in trouble as I do, please use it.

**Comment by balta2ar** [comment]
Does it support several dictionary files? I'm looking at this line of code and I'm not sure: https://github.com/yuki-ycino/ncm2-dictionary/blob/master/autoload/ncm2_dictionary.vim#L19

**Comment by yuki-ycino** [comment]
I use only a single dictionary file. I have missed multiple dictionaries.
I will fix it later.

**Comment by roxma** [comment]
The repo linik is added in wiki https://github.com/ncm2/ncm2/wiki
