### ISSUE TITLE
Cannot see the function param menu when using LanguageClient-neovim

### ISSUE THREAD

**Issue by HankelBao** [ncm2/ncm2#57]
I'd prefer to use Language Server for python completion but there is no preview window or pop-up menu when entering params of functions.

Is it because of incorrect settings? How can I solve it?

**Comment by HankelBao** [comment]
Here is the minimal vimrc that could reprocude the issue:

```
call plug#begin("~/.vim/plugged")
    Plug 'ncm2/ncm2'
    Plug 'roxma/nvim-yarp'
    autocmd BufEnter * call ncm2#enable_for_buffer()
    set completeopt=noinsert,menuone,noselect
    Plug 'autozimu/LanguageClient-neovim', {
        \ 'branch': 'next',
        \ 'do': 'bash install.sh',
        \ }
call plug#end()

let g:LanguageClient_serverCommands = {
    \ 'python': ['pyls'],
    \ 'vue': ['vls'],
    \ 'javascript': ['javascript-typescript-stdio']
    \ }
```

Here is the test python file:

```python
def test_func(a: int, b: int):
      return a+b
  
  
test_func(
```

The test_func could be auto completed, but I cannot see any info about the params after selecting test_func as the completion item.

If I use the plugin ncm2-jedi instead, I could see the params in the pop-up menu as I type. How can I see hints about params in prevew/pop-up menu if I use LanguageClient-neovim as completion source?

**Comment by roxma** [comment]
> The test_func could be auto completed, but I cannot see any info about the params after selecting  test_func as the completion item.
> 
> If I use the plugin ncm2-jedi instead, I could see the params in the pop-up menu as I type.

Actually this is  ncm2-jedi feature.  

> How can I see hints about params in prevew/pop-up menu if I use LanguageClient-neovim as completion source

It is impossible with current version.
