### ISSUE TITLE
How to make a better mixture of ncm2 source and LanguageClient source?

### ISSUE THREAD

**Issue by hackingcat** [ncm2/ncm2#60]
If you're having trouble with NCM2, Please provide the following information
along with your detailed issue description:

### OS
arch linux 
(If you're using Linux, sharing a reproducible, vimrc minimized docker image,
can definitely help solving the issue)

### neovim `:version` output
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.1/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
### Minimal vimrc for reproducing the issue
```
let g:ncm2#auto_popup=1
au User Ncm2PopupOpen set completeopt=noinsert,menuone,noselect
au User Ncm2PopupClose set completeopt=menuone
autocmd BufEnter * call ncm2#enable_for_buffer()
au TextChangedI * call ncm2#auto_trigger()

function! ExpandSnippetOrCarriageReturn()
    let snippet = UltiSnips#ExpandSnippet()
    if g:ulti_expand_res > 0
        return snippet
    else 
        return "\<C-y>"
    endif
endfunction

inoremap <expr> <CR> pumvisible() ? "<C-R>=ExpandSnippetOrCarriageReturn()<CR>" : "\<CR>"
function! Multiple_cursors_before()
    call ncm2#lock('vim-multiple-cursors')
endfunction

function! Multiple_cursors_after()
    call ncm2#unlock('vim-multiple-cursors')
endfunction

```
For some languages,just like python and cpp,I want to use ccls to cpp,but the ncm2-jedi is better than pyls.How to combine ncm2 source with LanguageClient better?

**Comment by roxma** [comment]
```vim
:echo keys(ncm2#_s('sources'))
['LanguageClient_python']
:call ncm2#override_source('LanguageClient_python', {'enable': 0})

:echo ncm2#_s('sources')['LanguageClient_python']
{'scope': ['python'], 'early_cache': 0, 'subscope_enable': 0, 'priority': 9, 'name': 'LanguageClient_python', 'complete_pattern': ['\.'], 'mark': 'LC', 'ready': 1, 'enable': 0, 'auto_popup':
 1, 'on_complete': 'LanguageClient_NCM2OnComplete'}
```

Put `call ncm2#override_source('LanguageClient_python', {'enable': 0})` into your vimrc.

**Comment by balta2ar** [comment]
Do you think this could be useful to add to the README or FAQ? The README mentions override_source, but not in the context of configuring LanguageClient servers.

**Comment by hackingcat** [comment]
Thank you.

**Comment by roxma** [comment]
@balta2ar 

I've added this link in the wiki: https://github.com/ncm2/ncm2/wiki
