### ISSUE TITLE
The plugin seems incompatible with jiangmiao/auto-pairs.

### ISSUE THREAD

**Issue by hackingcat** [ncm2/ncm2#61]
If you're having trouble with NCM2, Please provide the following information
along with your detailed issue description:

### OS

(If you're using Linux, sharing a reproducible, vimrc minimized docker image,
can definitely help solving the issue)

### Log files if you think the issue is a bug

```sh
export NVIM_PYTHON_LOG_FILE=/tmp/log
export NVIM_PYTHON_LOG_LEVEL=DEBUG
nvim
# reproduce the issue
```

**Comment by hackingcat** [comment]
https://asciinema.org/a/kex7qMm7RBN8XST5hwYQKcnf5

**Comment by hackingcat** [comment]
After you press **Space** or **{**,the buffer will insert  **<Plug>(ncm2_auto_trigger)**  by accident.

**Comment by roxma** [comment]
Unfortunately I cannot reproduce the issue:

```vim
execute 'source ' . $WORKSPACE_DIR . '/plug.vim'

call plug#begin($WORKSPACE_DIR)

Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
Plug 'ncm2/ncm2-bufword'
Plug 'ncm2/ncm2-jedi'
Plug 'jiangmiao/auto-pairs'

call plug#end()

set completeopt=noselect,menuone,noinsert

autocmd BufEnter * call ncm2#enable_for_buffer()
```

![ncm2-61](https://user-images.githubusercontent.com/4538941/43990444-8623ed02-9d8e-11e8-9f4b-26e46520c175.gif)

**Comment by hackingcat** [comment]
``` - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.local/share/nvim/plugged')
" Initialize plugin system

Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
Plug 'ncm2/ncm2-bufword'
Plug 'ncm2/ncm2-jedi'
Plug 'jiangmiao/auto-pairs'
Plug 'roxma/vim-paste-easy'

call plug#end()

set completeopt=noselect,menuone,noinsert

autocmd BufEnter * call ncm2#enable_for_buffer()
```
