### ISSUE TITLE
Possible to jump to autocomplete menu when it pops up? Also, enter and new line issue.

### ISSUE THREAD

**Issue by ali-alsabbah** [ncm2/ncm2#62]
In Sublime Text and VS Code, when the auto-complete menus pop up, hitting enter automatically selects the first thing that pops up. With ncm2, you have to scroll down one, then select it, then can move on. In addition, hitting enter without selecting anything just closes the menu rather going to new line. Can that behavior be changed as well?

**Comment by roxma** [comment]
:help completeopt

**Comment by ali-alsabbah** [comment]
@roxma what should I look for?

**Comment by roxma** [comment]
remove noselect from compleopt

**Comment by filipekiss** [comment]
@ali-alsabbah put this in your `.vimrc`:

`set completeopt-=noselect`

This should work.

**Comment by ali-alsabbah** [comment]
Thank you!
