### ISSUE TITLE
ncm2 with golang not compelete cross package

### ISSUE THREAD

**Issue by sanghai** [ncm2/ncm2#65]
:echo has("python3") print 1
:echo has("nvim-0.2.2") print 1
set rtp+=~/.config/dot/vi/
call plug#begin('~/.config/dot/vi/plugged/')
  Plug 'ncm2/ncm2'
  Plug 'roxma/nvim-yarp'
  Plug 'ncm2/ncm2-path'
  Plug 'ncm2/ncm2-go'
  Plug 'ncm2/ncm2-bufword'
call plug#end()

the ncm2 configure is setted as sugggested by Main Page.
complete works well with the same file, but it doesn't work well accross package.

**Comment by roxma** [comment]
Duplicated https://github.com/ncm2/ncm2-go/issues/2
