### ISSUE TITLE
auto expand candidate parameter while ncm2#enable_for_buffer()?

### ISSUE THREAD

**Issue by sanghai** [ncm2/ncm2#69]
If you're having trouble with NCM2, Please provide the following information
along with your detailed issue description:

### OS

(If you're using Linux, sharing a reproducible, vimrc minimized docker image,
can definitely help solving the issue)

### Log files if you think the issue is a bug

```sh
export NVIM_PYTHON_LOG_FILE=/tmp/log
export NVIM_PYTHON_LOG_LEVEL=DEBUG
nvim
# reproduce the issue
```

**Comment by roxma** [comment]
Your description is missing. Close for now.

**Comment by roxma** [comment]
> I need the feature of auto expand the candidate while i heat the (.

I'm not interested in this feature. Why not use [ncm2-ultisnips](https://github.com/ncm2/ncm2-ultisnips) ?

> how can i get the define show at the status like this and auto filled the parameter while i input like the damo show in HELPME.md?

Ncm2 doesn't have this feature. You probably need [echodoc](https://github.com/Shougo/echodoc.vim)
