### ISSUE TITLE
[feature request] Separate complete_length for manual trigger. 

### ISSUE THREAD

**Issue by LeOtaku** [ncm2/ncm2#70]
As mentioned in roxma/nvim-completion-manager#143 all manually triggered completion now behaves like auto-completion. However one of the uses manual completion had for me in ncm1 was triggering completion before the pmenu would show up automatically.

With this feature, specifying the following setting would allow manually triggering completion for all sources with a priority of higher than 5 at all times:
```vim
let g:ncm2#manual_complete_length = [[5,0]]
```

**Comment by roxma** [comment]
Please test https://github.com/ncm2/ncm2/pull/123
