### ISSUE TITLE
Using TypeScript Server as source for JavaScript files

### ISSUE THREAD

**Issue by caneta** [ncm2/ncm2#72]
Being [Tern project](https://github.com/ternjs/tern) not actively maintained anymore, I was wondering if it's foreseen support for [TypeScript Server](https://github.com/Microsoft/TypeScript/tree/master/src/server), which can be a valid alternative for JavaScript sources too.
Thank you.

**Comment by roxma** [comment]
IMO https://github.com/mhartington/nvim-typescript/pull/161 works for javascript, you could try it.

Or you could use a language client plugin such as https://github.com/autozimu/LanguageClient-neovim

**Comment by caneta** [comment]
I would like to use LanguageClient-neovim: I will check in the ncm2 docs how to configure it.
But just for curiosity: is the nvim-typescript plugin working with the same server?

**Comment by roxma** [comment]
Read https://jacky.wtf/weblog/language-client-and-neovim/ for LCN and ncm2

> But just for curiosity: is the nvim-typescript plugin working with the same server?

I'm not familiar with typescript. You could read its code to find out.

**Comment by caneta** [comment]
The Jacky post was great: very simple and worked like a charm!
Just changed `typescript` `javascript` in `LanguageClient_serverCommands` variable.
Thanks a lot @roxma!
