### ISSUE TITLE
Get Identifier info inside popup menu

### ISSUE THREAD

**Issue by caneta** [ncm2/ncm2#74]
I'm running neovim=0.3.2-dev on an Ubuntu Linux 14.04 machine and I'm using the [vscode-css-languageserver-bin](https://github.com/vscode-langservers/vscode-css-languageserver-bin) through the [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) plugin, having the following configuration:
```
autocmd BufEnter * call ncm2#enable_for_buffer()
set completeopt=noinsert,menuone,noselect
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
let g:LanguageClient_serverCommands = {'css': ['css-languageserver', '--stdio']}
```
With LanguageClient-neovim is possible to get **identifier info** with the `:call LanguageClient_textDocument_hover()` command ([animated gif here](https://github.com/autozimu/LanguageClient-neovim/issues/35#issuecomment-288731665)):

![neovimlspcomparison](https://user-images.githubusercontent.com/4066659/45036021-a9ad0080-b05b-11e8-8a30-5d902dfe50f5.png)

Is possible with ncm2 to have the same information inside a popup menu like vscode does?

![vscodelspcomparison](https://user-images.githubusercontent.com/4066659/45036064-bdf0fd80-b05b-11e8-876a-bda1762664d2.png)

Thank you.

**Comment by roxma** [comment]
I don't think this is possible on neovim.

**Comment by caneta** [comment]
Ok, but maybe is possible showing up this information in a separate split window.
There's an example of this behaviour in [this deoplete animated gif](https://github.com/callmekohei/deoplete-fsharp/blob/master/pic/sample.gif).

**Comment by roxma** [comment]
> Ok, but maybe is possible showing up this information in a separate split window.

This is vim/neovim feature. Please read  `:help completeopt`. It's basicly `set completeopt+=preview`. However personally I don't link it.  Every time the window gets shown, the current editting position suddenly jumps out of my focus, which is annoying.

**Comment by caneta** [comment]
Ok, I've tried `set completeopt+=preview` but no preview-window shows up with ncm2: is that feature implemented?
You're right, the focus issue would bother me too: it would be nice to keep the focus on the edit window.

**Comment by roxma** [comment]
> Ok, I've tried set completeopt+=preview but no preview-window shows up with ncm2: is that feature implemented?

It depends on the source. If no preview window is shown, it means that the  `info` field in `:help complete-items` is missing.

**Comment by caneta** [comment]
For JavaScript and CSS/SCSS with LanguageClient-neovim it does not work. An ncm2 source where I can see this behaviour?

**Comment by roxma** [comment]
To check the final item date: After the item gets completed, press <esc> to go back normal mode, then execute the command `:echo v:completed_item`

You could also enable ncm2 logging and `LanguageClient-neovim` logging to get more debugging information.

To enable ncm2 logging:

```sh
export NVIM_PYTHON_LOG_FILE=/tmp/log
export NVIM_PYTHON_LOG_LEVEL=DEBUG
nvim
# reproduce the issue
```

LanguageClient-neovim logging:

```vim
    let g:LanguageClient_loggingFile = '/tmp/lc.log'
    let g:LanguageClient_loggingLevel = 'DEBUG'
```

**Comment by caneta** [comment]
> To check the final item date: After the item gets completed, press to go back normal mode, then execute the command `:echo v:completed_item`

That worked and the info field is populated with the information i would like too see in the preview window...but it does not show up.
```
{'word': 'display: ', 'menu': '[ ] [LC] ', 'user_data': '{"source": "LanguageClient_css", "match_key": "abbr", "ncm2": 1, "match_highlig
ht": [[0, 3]], "ncm2_lspitem": {"kind": 10, "textEdit": {"range": {"end": {"line": 1, "character": 4}, "start": {"line": 1, "character":
 2}}, "newText": "display: "}, "documentation": "In combination with ''float'' and ''position'', determines the type of box or boxes tha
t are generated for an element.\n\nSyntax: [ <display-outside> || <display-inside> ] | <display-listitem> | <display-internal> | <displa
y-box> | <display-legacy>", "command": {"command": "editor.action.triggerSuggest", "title": "Suggest"}, "label": "display", "sortText":
"d"}, "startccol": 3, "snippet": "display", "is_snippet": false}', 'info': 'In combination with ''float'' and ''position'', determines t
he type of box or boxes that are generated for an element.

Syntax: [ <display-outside> || <display-inside> ] | <display-listitem> | <display-internal> | <display-box> | <display-legacy>', 'kind':
 'Property', 'abbr': 'display'}
```
Maybe something is missing in my conf?

**Comment by roxma** [comment]
You probably need to recheck your completeopt with `set completeopt`. I guess the `preview` gets overriden somewhere in your vimrc.

**Comment by caneta** [comment]
> I guess the preview gets overriden somewhere in your vimrc.

Yes, I was defining `completeopt` twice ini my init.vim...but now it works!
![previewwindow](https://user-images.githubusercontent.com/4066659/45080143-7bc7ca80-b0f4-11e8-9f35-085a465c9d64.png)

I don't feel annoyed by focus change by the way...thank you @roxma!
