### ISSUE TITLE
Need help on using with alchemist.vim

### ISSUE THREAD

**Issue by joshua7v** [ncm2/ncm2#79]
If you're having trouble with NCM2, Please provide the following information
along with your detailed issue description:

### OS

macOS

### neovim `:version` output

NVIM v0.3.1-156-g0ed8b12

alchemist.vim doesn't support ncm2 but deoplete is supported

So, I'm trying to move to ncm2, but elixir completion seems a little bit hard to set up.
Here's what I've tried
1. there's no 'official' ncm2 source for elixir
2. alchemist.vim provides omni completion, but ncm2's wrapper seems not working properly
3. elixir-ls (lsp) provides completion, but it completes with some argument placeholders for snippet use in vscode, in nvim environment, I cannot jump between these positions, and it makes this approach not usable.
4. finally try to forward deoplete's results to ncm2 (like in https://github.com/roxma/nvim-completion-manager/issues/50), but still, no luck

any suggestions?

**Comment by roxma** [comment]
> 2. alchemist.vim provides omni completion, but ncm2's wrapper seems not working properly

Please elaborate

> 3. elixir-ls (lsp) provides completion, but it completes with some argument placeholders for snippet use in vscode, in nvim environment, I cannot jump between these positions, and it makes this approach not usable.

You need to elaborate for this too

**Comment by joshua7v** [comment]
@bbtdev 

cool, thanks,
after switching to ultisnips from neosnippet, the problem has been solved
