### ISSUE TITLE
Is it possible to have completion from other buffers even if it is not async?

### ISSUE THREAD

**Issue by bbtdev** [ncm2/ncm2#80]
For example use the vim/nvim builtin completion as source?

**Comment by roxma** [comment]
There's no completion from other buffers currently.

As a workaround, I use `<c-y>` or `<c-e>` to close the popup menu, and manually use the builtin `<c-n>` to get completion from other buffer manually.

**Comment by fgrsnau** [comment]
[I did something like this](https://github.com/fgrsnau/ncm-otherbuf) for the previous version of ncm.

I assume it is not hard to port it to ncm2.

**Comment by fgrsnau** [comment]
I ported the source plugin to ncm2 (see `ncm2` branch). Actually, it was more complicated than expected (lack of ncm2 documentation).

You can give it a try if you want: `Plug 'fgrsnau/ncm-otherbuf', { 'branch': 'ncm2' }`

Your feedback is appreciated. :)

**Comment by tofulm** [comment]
Thanks !!

**Comment by pittcat** [comment]
@fgrsnau Good job.

**Comment by bbtdev** [comment]
@fgrsnau SALUTE

**Comment by roxma** [comment]
There's no need to keep this open anymore. Closing.
