### ISSUE TITLE
Question: how to only complete on <tab>?

### ISSUE THREAD

**Issue by Flink** [ncm2/ncm2#81]
Hi!

This plugin works very well so great work, I’m coming from deoplete and my experience wasn’t as good. (using language client and ruby)

I had this in my `.vimrc` which allowed me to complete only when hitting `tab` (I didn’t write this code though):
```vim
inoremap <silent><expr> <TAB>
			\ pumvisible() ?  "\<C-n>" :
			\ <SID>check_back_space() ? "\<TAB>" :
			\ deoplete#mappings#manual_complete()
function! s:check_back_space() abort ""
	let col = col('.') - 1
	return !col || getline('.')[col - 1]  =~ '\s'
endfunction ""
```
Now from what I understand if I want to do the same thing with ncm2, I should use `<Plug>(ncm2_manual_trigger)`. But when I try to use it, vim complains about an invalid expression :confused: This is the config:
```vim
inoremap <silent><expr> <TAB>
			\ pumvisible() ?  "\<C-n>" :
			\ <SID>check_back_space() ? "\<TAB>" :
			\ <Plug>(ncm2_manual_trigger)
```
I tried some variations of that but to no avail. Is there a way to achieve that with ncm2 please?

**Comment by roxma** [comment]
> I should use `<Plug>(ncm2_manual_trigger)`. But when I try to use it, vim complains about an invalid expression 

Use `"\<Plug>(ncm2_manual_trigger)"` in expression

**Comment by Flink** [comment]
Thanks for your answer but just tried and it actually inserts `<Plug>(ncm2_manual_trigger)` in the buffer where I hit tab instead of showing the popup :thinking:

**Comment by jasongraham** [comment]
You'll need to use `imap`, not `inoremap`.

**Comment by Flink** [comment]
Thanks @jasongraham, it’s working fine now :+1: :slightly_smiling_face:
