### ISSUE TITLE
Enable/disable completers/variables  based on file types

### ISSUE THREAD

**Issue by mortang2410** [ncm2/ncm2#82]
## Feature request / wiki suggestions etc.

Basically, I want to turn off the `'vim'` and `'*path'` sources while turning on `b:ncm2_look_enabled` whenever I'm editing *.txt files, so here is my solution for it.

```
if !exists("au_txt")
  let au_txt = 1
  let off_src = [ 'vim' , 'bufpath' , 'rootpath' , 'cwdpath' ]
  autocmd BufEnter *.txt :call Enter_txt(off_src) 
  autocmd BufLeave *.txt :call Leave_txt(off_src) 
endif

function! Enter_txt(off_src)
	for x in a:off_src
		call ncm2#override_source(x, {'enable': 0})
	endfor
	let b:ncm2_look_enabled = 1
endfunction

function! Leave_txt(off_src)
	for x in a:off_src
		call ncm2#override_source(x, {'enable': 1})
	endfor
endfunction


if !exists("au_txt")
  let au_txt = 1
  autocmd BufEnter *.txt :call Enter_txt() 
  autocmd BufLeave *.txt :call Leave_txt() 
endif
```
This is very crude of course. I wonder if this is the proper way of doing things with ncm2, e.g. 
- Does 'scope' allow 'vim' to exclude *.txt?
- Is there a way to enable / disable a completion source for just ONE buffer so that we don't have to provide 2 autocmds on entering / leaving?

If those features are missing, I can hope they can be added. Meanwhile, if my solution is good enough, I hope it can be put on the wiki, so that others might benefit from it.

**Comment by roxma** [comment]
Seems duplicated: https://github.com/ncm2/ncm2/issues/3
