### ISSUE TITLE
Improve incremental filtering behavior

### ISSUE THREAD

**Issue by ali-hardan** [ncm2/ncm2#83]
Hello. I have set g:ncm2#complete_delay to 1000.

I want to filter the output list by writing one letter. I know it must re-trigger to get new list because may exists new result, but I want to filter current results before the time of delay over. Just like omni.

Is it possible?

can I use omni with ncm2 results?

**Comment by roxma** [comment]
Do you want delay only for specific source?

If so, you could try the `'ncm2#on_complete#delay'` in the 'on_complete` option:

 `'on_complete': ['ncm2#on_complete#delay', 1000, 'ncm2#on_complete#omni', 'csscomplete#CompleteCSS']`

**Comment by ali-hardan** [comment]
I mean:

For example, when using pyclang, I write "gtk_", it take a time to get auto complete output from clang. after getting result, I want to filter them by typing a new char. for example, I add "w" character to filter results. now, my text is "gtk_w", but "gtk_about" is in the top of output list. popup list will be update after re-getting outputs. It  mean: popup list will be updated after seconds and user must wait.

I say: It should can filter current popup list, without needing to re-getting output, because it takes long time in some projects.

**Comment by dkasak** [comment]
I'd like this too. ncm2 is very fast, but is behaving very weirdly, with C-w not working in insert mode (the deleted completion just gets immediately reinserted) and a lot of kinds of the interface flickering. This makes it pretty much unusable but I'm not what the cause(s) are.

**Comment by roxma** [comment]
@dkasak 

I've never had the issues you described.

You need to open new issues with more information to reproduce the issue.

**Comment by dkasak** [comment]
@roxma Yes, it might be something in my config that's interacting badly with ncm2. I want to bisect my config to determine the cause or produce a minimal reproducing example, but I didn't have time to do that yet.

**Comment by roxma** [comment]
> I say: It should can filter current popup list, without needing to re-getting output, because it takes long time in some projects.

Please test #70
