### ISSUE TITLE
Do not sort if not required

### ISSUE THREAD

**Issue by balta2ar** [ncm2/ncm2#86]
Hello. I have a source with the following configuration (described here https://github.com/ncm2/ncm2/issues/21):
```
let g:ncm2_jira#source = get(g:, 'ncm2_jira#jira_source', {
            \ 'name': 'jira',
            \ 'priority': 9,
            \ 'mark': 'jira',
            \ 'word_pattern': 'JI\w*',
            \ 'complete_pattern': 'JI\w*',
            \ 'matcher': {'key': 'custom'},
            \ 'on_complete': 'ncm2_jira#on_complete',
            \ 'on_warmup': 'ncm2_jira#on_warmup'
            \ })
```

Here is how I make candidates:
```python
def get_jira_candidates(candidates, current_prefix, matcher_key):
    max_ticket_len = max(len(ticket) for ticket, _title in candidates)
    ticket_formatter = '%' + str(max_ticket_len) + 's'
    return [{'word': ticket,
             'abbr': ticket_formatter % ticket + ' ' + title,
             matcher_key: current_prefix + title, }
            for ticket, title in candidates]

class Source(Ncm2Source):
    def __init__(self, nvim):
        super(Source, self).__init__(nvim)

    def on_complete(self, ctx):
        query = ctx['base']

        candidates_filename = '~/.cache/jira/jira.candidates.tsv'
        candidates = load_lines(candidates_filename)
        matches = get_jira_candidates(candidates, query, 'custom')
        self.complete(ctx, ctx['startccol'], matches)
```

Basically my source is triggered by "JI" keyword, and then it provides candidates as follows:
```
{"word": "BSW_API_DEV-2687", "custom": "JI[GATE] Add feature flag to control proxying", "abbr": "      BSW_API_DEV-2687 [GATE] Add feature flag to control proxying", "icase": 1, "menu": "", "info": "", "kind": "", "user_data": {"source": "jira", "ncm2": 1, "snippet": "", "is_snippet": 0, "match_key": "custom", "match_highlight": [[0, 2]]}},
{"word": "POSTMORTEM-1063", "custom": "JIrelease caused problems in connected services", "abbr": "       POSTMORTEM-1063 release caused problems in connected services", "icase": 1, "menu": "", "info": "", "kind": "", "user_data": {"source": "jira", "ncm2": 1, "snippet": "", "is_snippet": 0, "match_key": "custom", "match_highlight": [[0, 2]]}},
```

Now the problem: on_complete produces candidates in some preferred order: more recent candidates go first, which is very convenient. However, when sorting is applied, they get mixed, and this is natural if my query is non-emptye, e.g. `JIproblem`, which `JI` is a prefix/trigger and `problem` is the query part. What I want is to skip sorting if my query is empty, for example just `JI`. In this case I'd like to just display candidates in the order that `on_complete` handler produced them.

I tried overriding Source, but it seems that it is not provided information about the currently typed word, it is only given matches that need to be sorted.

What's the best way to do that? Is it possible without changing the core?

**Comment by roxma** [comment]
You could use the `none` sorter for the source.

- Then you could use `refresh=True` in the `self.complete` call and do your own sorting in the source.
- Or  you could customize the sort using the `filter` option. `pythonx/ncm2_filter/same_word.py` is an example.
