### ISSUE TITLE
ncm2 doesn't work

### ISSUE THREAD

**Issue by huyvohcmc** [ncm2/ncm2#9]
### OS

Mac OS 10.13.4

### neovim `:version` output

0.3.0

### Minimal vimrc for reproducing the issue

```
Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'

autocmd BufEnter * call ncm2#enable_for_buffer()
inoremap <expr> <CR> (pumvisible() ? "\<c-y>\<cr>" : "\<CR>")
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

set completeopt=noinsert,menuone,noselect
set shortmess+=c
```

### Issue

The auto-completion popup never appears no matter what even though all the requirements are meet. I don't know but I might consider to revert [this commit](https://github.com/huyvohcmc/dotfiles/commit/9192ef07a73c33ee7ece98735557e114ae806cda).

**Comment by roxma** [comment]
That’s the expected behavior. You havent install any completion source.
