### ISSUE TITLE
<Plug>(ncm2_auto_trigger) output on paste

### ISSUE THREAD

**Issue by tanc** [ncm2/ncm2#92]
### OS
Linux Ubuntu 18.04

### neovim `:version` output
NVIM v0.3.0

I'm just getting started with a Neovim set up so I'm not an expert by any stretch. I'm finding that when pasting I'm sometimes getting `<Plug>(ncm2_auto_trigger)` appended to the clipboard pasted contents. This can sometimes be appended many times for a single paste and look like this:

```
          if (this.$route.params.package) {
                    this.package = this.$route.params.package
                    this.requestData()
                  }
        },<Plug>(ncm2_auto_trigger)<Plug>(ncm2_auto_trigger)<Plug>(ncm2_auto_trigger)<Plug>(ncm2_auto_trigger)<Plug>(ncm2_auto_trigger)<Plug>(ncm2_auto_trigger)<Plug>(ncm2_auto_trigger)<Plug>(ncm2_auto_trigger)
```

The only other result I could find was this issue: #61 
I don't have either of those plugins installed though.
My nvim config is here: https://github.com/tanc/dotfiles/blob/master/.config/nvim/init.vim

Is there anything I can do to help debug?

**Comment by ObserverOfTime** [comment]
I'm also having this issue and I tried multiple ways to solve it, but none worked.

I set `nopaste` in my nvim config, but paste mode gets activated randomly at times and this issue appears.
I disabled all other plugins, but nothing changed.

So, I checked ncm2's code and found that it was using `feedkeys()` with `<Plug>(ncm2_auto_trigger)`.
However, ncm2 checks if paste mode is on before doing so, which means that isn't the problem.

Finally, I added an `autocmd` for `OptionSet paste` to turn on a flag and prevent `feedkeys()` from executing. This worked, but the flag couldn't be turned off.
When I altered it so the flag could be turned off, the issue reappeared.

After that, I gave up.

**Comment by roxma** [comment]
This issue is hard to fix. I have post a feature request to neovim: https://github.com/neovim/neovim/issues/9202

The best alternative currently, is to figure-out the plugin that turn your neovim into paste mode, then use `:help ncm2#lock()`  and `ncm2#unlock` for workaround.

**Comment by ObserverOfTime** [comment]
The issue persisted after I disabled all plugins, but I can try again with a very mininal vimrc and see what happens.

**Comment by ObserverOfTime** [comment]
The issue is still reproducible with this vimrc:
```vim
call plug#begin('/tmp/ncm2-test')

Plug 'roxma/nvim-yarp'
Plug 'ncm2/ncm2'
" Plug 'cwis-public/ncm2', {'commit': 'bb0564a'}
" Plug 'ncm2/ncm-bufword'
Plug 'ncm2/ncm2-path'

call plug#end()

set completeopt=noinsert,noselect,menuone

augroup NCM2Test
    au!
    au VimEnter * call ncm2#enable_for_buffer()
augroup END
```
I tried different autocompletion sources, and even #95, but the issue is still there.
It's not a plugin that's causing it. So, it's either a NCM2 issue, or an inherent issue of Neovim.

**Comment by roxma** [comment]
Please test this branch https://github.com/ncm2/ncm2/pull/99

**Comment by Avi-D-coder** [comment]
This is still a problem, even with #99.

**Comment by roxma** [comment]
Unfortunately I think this issue is hard to fixed.

Optimally there should be some kind of features like https://github.com/neovim/neovim/issues/9202 implemented on vim or neovim side.

//  cc @brammool @justinmk

**Comment by roxma** [comment]
@Avi-D-coder  Please teset https://github.com/ncm2/ncm2/pull/106

**Comment by Avi-D-coder** [comment]
I have been using your patch. The issue seems to be resolved. Thank you for fixing this.
