### ISSUE TITLE
Is ncm2 compatible with ncm-R?

### ISSUE THREAD

**Issue by hughshuwang** [ncm2/ncm2#98]
Look forward to having auto completion by ncm-R and ncm2. Just wondering is there any test done for this?

**Comment by gaalcaras** [comment]
I took me some time, but I'm working on it :fireworks: . Please give your feedback over at https://github.com/gaalcaras/ncm-R/issues/13

**Comment by hughshuwang** [comment]
Thanks for your time! Will continue the discussion if necessary at #13.
